# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-06 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlikes',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productlikes',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='productcomments',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductLikes',
        ),
    ]
