# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170707_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlikes',
            name='text',
            field=models.IntegerField(default=1),
        ),
    ]
